/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/shoes.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoes.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={10.465}>
        <mesh geometry={nodes.Retopo_3DModel_mesh002.geometry} material={materials['3DModel_Custom.002']} />
        <mesh geometry={nodes.Retopo_3DModel_mesh002_1.geometry} material={materials['3DModel_Custom.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/shoes.glb')
